steps:
  build-and-push-tag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER##mu-}/mu-${CI_REPO_NAME}
      tags: ${CI_COMMIT_TAG##v}
      platforms: linux/amd64
    secrets: [ docker_username, docker_password ]
when:
  - event: tag
